order_management/urls.py
from django.urls import path
from.import views
app_name = 'order_management'

urlpatterns=[
    path('wishlist/',views.wishlist,name='wishlist'),
    path('add_to_wishlist/<int:product_id>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('remove_from_wishlist/<int:product_id>/',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('cart',views.cart,name='cart'),
    path('add_to_cart/<int:product_id>/',views.add_to_cart,name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/cart',views.remove_from_cart,name='remove_from_cart'),
    path('confirmation',views.confirmation,name='confirmation'),
    path('checkout',views.checkout,name='checkout'),
    path('remove_cart_quantity/<int:product_id>/',views.remove_cart_quantity,name='remove_cart_quantity'),
    path('add_cart_quantity/<int:product_id>/',views.add_cart_quantity,name='add_cart_quantity'),
    path('proceed_to_pay/',views.razorPayCheck,name="razorpaycheck"),
    path('place_order/', views.placeOrder, name='place_order'),
    path('order-complete/',views.orderComplete, name='order_complete'),
    path('cancel-order/<int:id>/',views.cancelOrder, name='cancel_order'),
]
        






    

product_management/urls.py
from django.urls import path
from.import views

app_name='product_management'
urlpatterns=[
    path('productlist/<int:pid>/',views.productlists,name='productlist'),
    path('singleproductview/<int:id>/',views.singleproductview,name='singleproductview'),
    path('search',views.search,name='search')

]

shoeplaza/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_management.urls')),
    path('adminpanel/', include('admin_management.urls')),
    path('', include('product_management.urls')),
    path('', include('order_management.urls')),
    path('', include('further_management.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/products/listproduct.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<br><br><br><br><br>

<div class="container">
    <div class="row">
        <div class="col-xl-3 col-lg-4 col-md-5">
            <div class="sidebar-categories">

                <div class="head">Browse Categories</div>

                <ul class="main-categories">
                    
                    <li class="main-nav-list"><a href="{% url 'product_management:productlist' 0 %}"> All Categories</a>
                    </li>
                    {% for c in categories %}
                    <li class="main-nav-list"><a href="{% url 'product_management:productlist' c.id %}">{{ c.category_name }}</a>
                   </li>
                 {% endfor %}
                </ul>
</div>
        </div>
        <div class="col-xl-9 col-lg-8 col-md-7">
            <!-- Start Filter Bar -->
            <div class="filter-bar d-flex flex-wrap align-items-center">
                            <div>
                                <nav aria-label="Page navigation example">
                                    <ul class="pagination justify-content-center">
                                        {% if page_obj.has_previous %}
                                            <li>
                                                <a class="page-link" href="?page=1{% if keyword %}&keyword={{ keyword }}{% endif %}" aria-label="First">
                                                    <i class="ti-angle-double-left"></i>
                                                </a>
                                            </li>
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}{% if keyword %}&keyword={{ keyword }}{% endif %}" aria-label="Previous">
                                                    <i class="ti-angle-left"></i>
                                                </a>
                                            </li>
                                        {% endif %}
                                        {% for page in page_obj.paginator.page_range %}
                                            {% if page_obj.number == page %}
                                                <li class="page-item active"><a class="page-link" href="#">{{ page }}</a></li>
                                            {% elif page > page_obj.number|add:'-3' and page < page_obj.number|add:'3' %}
                                                <li class="page-item"><a class="page-link" href="?page={{ page }}{% if keyword %}&keyword={{ keyword }}{% endif %}">{{ page }}</a></li>
                                            {% endif %}
                                        {% endfor %}
                                        {% if page_obj.has_next %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ page_obj.next_page_number }}{% if keyword %}&keyword={{ keyword }}{% endif %}" aria-label="Next">
                                                    <i class="ti-angle-right"></i>
                                                </a>
                                            </li>
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{% if keyword %}&keyword={{ keyword }}{% endif %}" aria-label="Last">
                                                    <i class="ti-angle-double-right"></i>
                                                </a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                </nav>
                            </div>

                <div style="margin-left: 165px; margin-top: 10px;" class="single_product_menu d-flex ">
                    <form method="GET" action="{% url 'product_management:search' %}" class="d-flex">
                        <input type="text" class="form-control me-2" name="keyword" placeholder="Search" aria-label="Search">
                       &nbsp;&nbsp;&nbsp;
                        <button class=" btn btn-info success " style="border-radius: 10px ;"type="submit">Search</button>
                    </form>
                </div>

            </div>
            
            <!-- End Filter Bar -->
            <!-- Start Best Seller -->
            <section class="lattest-product-area pb-40 category-list">
                <div class="row">
                    {% for p in page_obj  %}

                    <!-- single product -->
                    <div class="col-lg-4 col-md-6">
                        <div class="single-product">
                            <a href="{% url 'product_management:singleproductview' p.id %}">
                                <img class="img-fluid" src="{{p.images.url}}" alt="">
                            </a>
                            <div class="product-details">
                                <h6>{{ p.product_name }}</h6>
                                <div class="price">
                                    <h6>₹ {{ p.price }}</h6>
                                    <h6 class="l-through">₹ 2100.00</h6>
                                </div>

                                <div class="prd-bottom">

                                    <a href="{% url 'order_management:add_to_cart' p.id %}" class="social-info">
                                        <span class="ti-bag"></span>
                                        <p class="hover-text">add to cart</p>
                                    </a>
                                    <a href="{% url 'order_management:add_to_wishlist' p.id %}" class="social-info">
                                        <span class="lnr lnr-heart"></span>
                                        <p class="hover-text">Wishlist</p>
                                    </a>
                                    <a href=" {% url 'product_management:singleproductview' p.id %}" class="social-info">
                                        <span class="lnr lnr-move"></span>
                                        <p class="hover-text">view more</p>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}

                </div>
            </section>
            <!-- End Best Seller -->

        </div>
    </div>
</div>
<br><br><br><br><br><br>

{% endblock %}

templates/products/singleproductview.html
{% extends 'base.html' %}
{% load static %}
{% block content %} 

	<!--================Single Product Area =================-->
	<div class="product_image_area">

		<div class="container">
			<div class="row s_product_inner">
				<div class="col-lg-6">
					<div class="s_Product_carousel">
						<div class="single-prd-item">
							<img class="img-fluid big_img" src="{{product.images.url}}" alt="">
						</div>
						<div class="single-prd-item">
							<img class="img-fluid big_img" src="{{product.images.url}}" alt="">
						</div>
						<div class="single-prd-item">
							<img class="img-fluid big_img" src="{{product.images.url}}" alt="">
						</div>
					</div>
				</div>
				<div class="col-lg-5 offset-lg-1">
					<div class="s_product_text">
						<h3>{{product.product_name}}</h3>
						<h2>₹ {{product.price}}</h2>
						<ul class="list">
							<li><a class="active" href="#"><span>Category</span> {{product.category}}</a></li>
							{% if product.stock > 0 %}
							<li><a href="#"><span>Availibility</span> : In Stock</a></li>
							{% else %}
							<li><a href="#"><span>Availibility</span> : Out of Stock</a></li>
							{% endif %}

						</ul>
						<p>{{product.description}}</p>
					    <div class="card_area d-flex align-items-center">
							<div class="details-action-col col-7"> 
								{% if product.stock > 0 %} 
								<form action="{% url 'order_management:add_to_cart' product.id %}" method="POST">
									{% csrf_token %}
									<div class="d-flex justify-content-center align-items-space-between">
								
										<label class="mt-2 h6">Quantity:</label>
						
										<input type="number" class="form-control form-control-md" name="quantity" value="1" min="1" max="10" step="1" required style="width: 100%; max-width: 200px;">
										
										<input type="hidden" name="product_id" value="{{ product.id }}">
										&nbsp&nbsp <button type="submit" class="btn btn-warning " style=" margin-right:-12px; background: linear-gradient(90deg, #ffba00 0%, #ff6c00 100%);  color: #f2f2f2;"><i class="bi bi-cart-plus" ></i> Add to Cart</button>
	
									</div>

								</form>
								{% else %}
								<a href="" class="btn btn-block btn-outline-primary-2 disabled">Out of Stock</a>
								{%endif%}    
							</div>                       
					       <a class="icon_btn" href="{% url 'order_management:add_to_wishlist' product.id %}"><i class="lnr lnr lnr-heart"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!--================End Single Product Area =================-->

<br><br><br>

{% endblock  %}