further_management/urls.py
from django.urls import path
from.import views

app_name='further_management'

urlpatterns=[
       path('myorders/',views.myorders,name='myorders'),
       path('vieworder/<int:id>/',views.viewOrder, name='vieworder'),

]

order_management/urls.py
from django.urls import path
from.import views
app_name = 'order_management'

urlpatterns=[
    path('wishlist/',views.wishlist,name='wishlist'),
    path('add_to_wishlist/<int:product_id>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('remove_from_wishlist/<int:product_id>/',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('cart',views.cart,name='cart'),
    path('add_to_cart/<int:product_id>/',views.add_to_cart,name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/cart',views.remove_from_cart,name='remove_from_cart'),
    path('confirmation',views.confirmation,name='confirmation'),
    path('checkout',views.checkout,name='checkout'),
    path('remove_cart_quantity/<int:product_id>/',views.remove_cart_quantity,name='remove_cart_quantity'),
    path('add_cart_quantity/<int:product_id>/',views.add_cart_quantity,name='add_cart_quantity'),
    path('proceed_to_pay/',views.razorPayCheck,name="razorpaycheck"),
    path('place_order/', views.placeOrder, name='place_order'),
    path('order-complete/',views.orderComplete, name='order_complete'),
    path('cancel-order/<int:id>/',views.cancelOrder, name='cancel_order'),
]
        






    

product_management/urls.py
from django.urls import path
from.import views

app_name='product_management'
urlpatterns=[
    path('productlist/<int:pid>/',views.productlists,name='productlist'),
    path('singleproductview/<int:id>/',views.singleproductview,name='singleproductview'),
    path('search',views.search,name='search')

]

shoeplaza/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_management.urls')),
    path('adminpanel/', include('admin_management.urls')),
    path('', include('product_management.urls')),
    path('', include('order_management.urls')),
    path('', include('further_management.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/further/myorders.html
{% extends 'base.html' %}
{% block content %}

<section class="section-conten padding-y bg" style="margin-top: 100px">
  <div class="container card mb-5" style="background-color: white">
    <div class="row">

      <main class="col-md-12">
        {% include 'include/messagealert.html' %}

        <article class="card my-4">

          {%if orders%}
          <header class="card-header" style="background-color: #ffffff">
            <h3><strong class="d-inline-block mr-3">My orders</strong></h3>
          </header>
          <div class="card">
            <div class="card-body">
              <table class="table table-borderless">
                <thead class="text-muted">
                  <tr class="small text-uppercase">
                    <th scope="col">order date</th>
                    <th scope="col">Tracking Number</th>
                    <th scope="col">Total Price</th>
                    <th scope="col">Payment ID</th>
                    <th scope="col">Status</th>
                    <th scope="col">Action</th>
                  </tr>
                </thead>

                <tbody>
                  {% for item in orders %}
                  <tr>
                    <td>{{ item.created_at }}</td>
                    <td>{{ item.order_number }}</td>
                    <td>₹ {{ item.order_total }}</td>
                    <td>
                    {{ item.payment.payment_id }}
                    </td>
                    {% if item.status == 'Cancelled' %}
                    <td ><b class="text-danger">{{ item.status }}</b></td>
                    {% else %}
                    <td >
                      <b class="text-success">{{ item.status }}</b>
                    </td>
                    {% endif %}

                    <td>
                      <a href="{% url 'further_management:vieworder' item.id %}"class="btn btn-dark">View</a >
                    </td>
                  </tr>

                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
          {%else%}
          <div>
            <h2 class="text-center">Your order history is empty</h2>
            <div class="text-center">
              <a class="btn_1" href="{% url 'product_management:productlist' 0 %}">Continue shopping..</a>
            </div>
          </div>
          {%endif%}
        </article>
        <!-- order-group.// -->
      </main>
    </div>
    <!-- row.// -->
  </div>
</section>

{% endblock %}

templates/further/vieworder.html
{% extends 'base.html' %} {% load static%} {% block content %}

<div class="container my-3">
  {% include 'include/messagealert.html' %}

  <div class="row">
    <div class="col-md-12" style="margin-top: 70px">
      <div class="card shadow" style="margin-top: 40px; padding-left: 23px">
        <div class="card-header">
          <h3>View order</h3>
          <a href="{%url 'further_management:myorders'%}" class="btn-3 float-end">
            <i class="fa fa-reply"></i> Back</a
          >
        </div>
        <div class="card-body">
          <div class="row">
            <div class="col-md-6">
              <h4>Shipping Details</h4>
              <hr />
              <label class="mt-2"> Name</label>
              <div class="border p-1">
                {{order.address.full_name}}
              </div>

              <label class="mt-2">Email</label>
              <div class="border p-1">{{order.address.email}}</div>
              <label class="mt-2">Phone Number</label>
              <div class="border p-1">{{order.address.phone}}</div>
              <label class="mt-2">Delivery Address</label>
              <div class="border p-1">
                {{order.address.full_address}} <br />
              </div>
            </div>
            <div class="col-md-6">
              <h4>Order Details</h4>
              <table class="table table-borderless">
                <thead class="text-muted">
                  <tr class="small text-uppercase">
                    <th scope="col">Product</th>
                    <th scope="col">Quantity</th>
                    <th scope="col">Price</th>
                    <th scope="col"></th>
                  </tr>
                </thead>
                <tbody>
                  {% for item in orderitems %}
                  <tr>
                    <td>
                      <figure class="itemside align-items-center">
                        <div class="how-itemcart1">
                          <img
                            src="{{ item.product.images.url }}"
                            style="height: 100px; width: 100px;"
                            alt="IMG"
                          />
                        </div>
                      </figure>
                    </td>
                    <td>
                        {{item.product.product_name}}
                    </td>
                    <td class="column">
                      <label class="my-3" for="">{{ item.quantity }}</label>
                    </td>
                    <td>
                      <div class="price-wrap">
                        <var class="price">₹{{ item.product_price }}</var><br/>
                        <small class="text-muted">
                          ₹{{ item.product.price}} each
                        </small>
                      </div>
                      <!-- price-wrap .// -->
                    </td>
                  </tr>
                  {% endfor %}
                </tbody></table>
              <hr />
              <div>
                <h5 class="d-flex align-end">
                  Total : ₹{{order.order_total}}
                <br />
                Coupon Applied : {{userCoupon_set.coupon.code}}
                <br />
                Grand Total: ₹{{order.paid_amount}}
                <br />
                </h5>
                <br />
                <h6>Payment Mode : {{order.payment.payment_method}}</h6>
                <br />
                {% if order.status == 'Cancelled' %}
                <h6>
                  Order Status:
                  <span class="text-danger">{{order.status}}</span>
                </h6>
                <br />
                {% elif order.status == 'Pending' %}
                <h6>
                  Order Status:
                  <span class="text-warning">{{order.status}}</span>
                </h6>
                <br />
                {% else %}
                <h6>
                  Order Status:
                  <span class="text-success">{{order.status}}</span>
                </h6>
                <br />
                {% endif %}
                <h6>Tracking Number : {{order.order_number}}</h6>
                <br />
                <h6>Payment ID : {{order.payment.payment_id}}</h6>
                <br />
              </div>
              <div class="d-flex justify-content-end">
                {% if order.status != 'Cancelled' %}
                <a href="{% url 'order_management:cancel_order' order.id %}"
                  ><button class="btn btn-danger" id ="refundButton">Cancel Order</button></a
                >

                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


{% endblock %}