further_management/urls.py
from django.urls import path
from.import views

app_name='further_management'

urlpatterns=[
       path('myorders/',views.myorders,name='myorders'),
       path('vieworder/<int:id>/',views.viewOrder, name='vieworder'),

]

order_management/urls.py
from django.urls import path
from.import views
app_name = 'order_management'

urlpatterns=[
    path('wishlist/',views.wishlist,name='wishlist'),
    path('add_to_wishlist/<int:product_id>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('remove_from_wishlist/<int:product_id>/',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('cart',views.cart,name='cart'),
    path('add_to_cart/<int:product_id>/',views.add_to_cart,name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/cart',views.remove_from_cart,name='remove_from_cart'),
    path('confirmation',views.confirmation,name='confirmation'),
    path('checkout',views.checkout,name='checkout'),
    path('remove_cart_quantity/<int:product_id>/',views.remove_cart_quantity,name='remove_cart_quantity'),
    path('add_cart_quantity/<int:product_id>/',views.add_cart_quantity,name='add_cart_quantity'),
    path('proceed_to_pay/',views.razorPayCheck,name="razorpaycheck"),
    path('place_order/', views.placeOrder, name='place_order'),
    path('order-complete/',views.orderComplete, name='order_complete'),
    path('cancel-order/<int:id>/',views.cancelOrder, name='cancel_order'),
]
        






    

product_management/urls.py
from django.urls import path
from.import views

app_name='product_management'
urlpatterns=[
    path('productlist/<int:pid>/',views.productlists,name='productlist'),
    path('singleproductview/<int:id>/',views.singleproductview,name='singleproductview'),
    path('search',views.search,name='search')

]

shoeplaza/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_management.urls')),
    path('adminpanel/', include('admin_management.urls')),
    path('', include('product_management.urls')),
    path('', include('order_management.urls')),
    path('', include('further_management.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/changepassword.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--================Login Box Area =================-->
<section class="login_box_area section_gap">
    <div class="container">
        <div class="row">
            <div class="col-lg-6" >
                <div class="login_box_img">
                    <img class="img-fluid" src="{% static 'img/signup19.jpeg' %}" alt="">
                </div>
            </div>
            
            <div class="col-lg-6">
                
                <div class="login_form_inner">
                    <br/>
            <br/>
            {% include 'include/messagealert.html' %}
            <br/>
                    <h3>Change your password</h3>
                    <form class="row login_form" action="{% url 'changepassword'%}" method="post" id="contactForm" >
                    {% csrf_token %}
                        <div class="col-md-12 form-group">
                            <input type="password" class="form-control"  name="current_password" placeholder="Your Password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Your Password'">
                        </div>

                        <div class="col-md-12 form-group">
                            <input type="password" class="form-control"  name="new_password" placeholder="New Password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'New Password'">
                        </div>
                        <div class="col-md-12 form-group">
                            <input type="password" class="form-control"  name="confirm_password" placeholder="Confirm Password" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Confirm Password'">
                        </div>
                        <div class="col-md-12 form-group">
                            <button type="submit" value="submit" class="primary-btn">Confirm</button>
                            <a href="{% url 'forgetpassword'%}">Forgot Password?</a>
                        </div>

                       
                    
                    
                    
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Login Box Area =================-->
{% endblock %}

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx" class="no-js">

<head>
	<!-- Mobile Specific Meta -->
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="img/fav.png">
	<!-- Author Meta -->
	<meta name="author" content="CodePixar">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>ShoePlaza</title>
	<!--
		CSS
		============================================= -->
	<link rel="stylesheet" href="{% static '/css/linearicons.css' %}">
	<link rel="stylesheet" href="{% static '/css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static '/css/themify-icons.css' %}">
	<link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static '/css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static '/css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static '/css/nouislider.min.css' %}">
	<link rel="stylesheet" href="{% static '/css/ion.rangeSlider.css' %}">
	<link rel="stylesheet" href="{% static '/css/ion.rangeSlider.skinFlat.css' %}">
	<link rel="stylesheet" href="{% static '/css/magnific-popup.css' %}">
	<link rel="stylesheet" href="{% static '/css/main.css' %}">
	<link rel="stylesheet" href="https://unpkg.com/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
	<style>
		.banner-area {
	background: url(../img/banner/banner-bg.jpg) center no-repeat;
	background-size: cover;
	position: relative;
	.fullscreen {
		@media (max-width: 768px) {
			height: 650px !important;
		}
	}
	</style>
</head>
<header class="header_area sticky-header">
    <div class="main_menu">
        <nav class="navbar navbar-expand-lg navbar-light main_box">
            <div class="container">
                <!-- Brand and toggle get grouped for better mobile display -->
                <a class="navbar-brand" >
                    <img src="{% static 'img/logo1.png' %}" alt="" class="w-25 h-25">
                  </a>
				  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Collect the nav links, forms, and other content for toggling -->
                <div class="collapse navbar-collapse offset" id="navbarSupportedContent">
                    <ul class="nav navbar-nav menu_nav ml-auto">
						{% if request.user.is_superuser%}
						<li class="nav-item "><a class="nav-link" href="{% url 'admindashboard' %}">Admin</a></li>
                        {% endif %}
                        <li class="nav-item "><a class="nav-link" href="{% url 'homepage' %}">Home</a></li>
						<li class="nav-item"><a class="nav-link" href="{% url 'product_management:productlist' 0 %}">Shop</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">About</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">Contact</a></li>     
                              
                        <li class="nav-item">
                            {% if request.user.is_authenticated %}
                            <a class="nav-link" href="{% url 'userprofile' %}">
                                My profile
                            </a>
                            {% else %}
                            <a class="nav-link" href="{% url 'userloginpage' %}">
                                Login
                              <i class="bi bi-person" style="font-size: 1rem;"></i>
                            </a>
                            {% endif %}
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'order_management:cart' %}">
                                
                              <i class="bi bi-cart" style="font-size: 1rem;"></i>
                            </a>
                          </li>
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'order_management:wishlist' %}">
                                
                              <i class="bi bi-heart" style="font-size: 1rem;"></i>
                            </a>
                          </li>
						{% if request.user.is_authenticated %}
                        <form action="{% url 'logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class=" btn btn-warning btn-sm  border-0 mt-2 " style="background: linear-gradient(90deg, #ffba00 0%, #ff6c00 100%); color: #f2f2f2;">Logout</button>
                        </form>
						{% endif %}  
                    </ul>
                    
                </div>
            </div>
        </nav>
    </div>
</header>
	<!-- start banner Area -->

	<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
		<div class="carousel-inner">
		  <div class="carousel-item active">
			<img class="d-block w-100" src="{% static 'img/banner/banner-bg.jpg' %}" alt="First slide">
		  </div>
        {% for b in banner %}
		  <div class="carousel-item">
			<img class="d-block w-100" src="{{b.images.url}}" alt="Second slide">
			<div class="carousel-caption">
				<h1><strong><i>{{ b.title }}</i></strong></h1>
				<h3 class="text-danger"><strong><i>{{ b.description }}</i></strong></h3>
				<a href="{% url 'product_management:productlist' 0 %}" class="btn btn-warning">Shop Now</a>
			  </div>
		  </div>
		{% endfor %}
		</div>
		<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
		  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
		  <span class="sr-only">Previous</span>
		</a>
		<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
		  <span class="carousel-control-next-icon" aria-hidden="true"></span>
		  <span class="sr-only">Next</span>
		</a>
	  </div>
	{% comment %} <section class="banner-area">
		<div class="container">
			<div class="row fullscreen align-items-center justify-content-start">
				<div class="col-lg-12">
				
						<!-- single-slide -->
						<div class="row single-slide align-items-center d-flex">
							<div class="col-lg-5 col-md-6">
								<div class="banner-content">
									<h1>ShoePlaza New <br>Collection!</h1>
									
									<div class="add-bag d-flex align-items-center">
										<a class="add-btn" href=""><span class="lnr lnr-cross"></span></a>
										<span class="add-text text-uppercase">Add to Bag</span>
									</div>
								</div>
							</div>
							<div class="col-lg-7">
								<div class="banner-img">
									<img class="img-fluid" src="{% static 'img/banner/banner-img.png' %}" alt="">
								</div>
							</div>
						</div>
						</div>
				</div>
			</div>
		</div>
	</section> {% endcomment %}
	<!-- End banner Area --> 
{% comment %} <br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br> {% endcomment %}

	 <!-- start features Area -->
	<section class="features-area section_gap">
		<div class="container">
			<div class="row features-inner">
				<!-- single features -->
				<div class="col-lg-3 col-md-6 col-sm-6">
					<div class="single-features">
						<div class="f-icon">
							<img src="{% static 'img/features/f-icon1.png' %}" alt="">
						</div>
						<h6>Free Delivery</h6>
						<p>Free Shipping on all order</p>
					</div>
				</div>
				<!-- single features -->
				<div class="col-lg-3 col-md-6 col-sm-6">
					<div class="single-features">
						<div class="f-icon">
							<img src="{% static 'img/features/f-icon2.png' %}" alt="">
						</div>
						<h6>Return Policy</h6>
						<p>Free Shipping on all order</p>
					</div>
				</div>
				<!-- single features -->
				<div class="col-lg-3 col-md-6 col-sm-6">
					<div class="single-features">
						<div class="f-icon">
							<img src="{% static 'img/features/f-icon3.png' %}" alt="">
						</div>
						<h6>24/7 Support</h6>
						<p>Free Shipping on all order</p>
					</div>
				</div>
				<!-- single features -->
				<div class="col-lg-3 col-md-6 col-sm-6">
					<div class="single-features">
						<div class="f-icon">
							<img src="{% static 'img/features/f-icon4.png' %}" alt="">
						</div>
						<h6>Secure Payment</h6>
						<p>Free Shipping on all order</p>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- end features Area -->

	<section class=""> 

	 <!-- single product slide -->
		<div class="single-product-slider">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-lg-6 text-center">
						<div class="section-title">
							<h1>Latest Products</h1>
							<p>Discover our latest shoe collection, offering a wide range of styles for every occasion. From casual sneakers to dress shoes, find your perfect fit.</p>
						</div>
					</div>
				</div>
				<div class="row">
			{% for p in products_latest %}

			<!-- single product -->
			<div class="col-lg-3 col-md-6">
				<div class="single-product">
					<a href="{% url 'product_management:singleproductview' p.id %}">
						<img class="img-fluid" src="{{p.images.url}}" alt="">
					</a>
					<div class="product-details">
						<h6>{{ p.product_name }}</h6>
						<div class="price">
							<h6>₹ {{ p.price }}</h6>
							<h6 class="l-through">₹ 2100.00</h6>
						</div>

						<div class="prd-bottom">

							<a href="{% url 'order_management:add_to_cart' p.id %}" class="social-info">
								<span class="ti-bag"></span>
								<p class="hover-text">add to cart</p>
							</a>
							<a href="{% url 'order_management:add_to_wishlist' p.id %}" class="social-info">
								<span class="lnr lnr-heart"></span>
								<p class="hover-text">Wishlist</p>
							</a>
							<a href=" {% url 'product_management:singleproductview' p.id %}" class="social-info">
								<span class="lnr lnr-move"></span>
								<p class="hover-text">view more</p>
							</a>
						</div>
					</div>
				</div>
			</div>
			{% endfor %}
		<!-- single product slide -->
		<div class="single-product-slider">
			<div class="container">
				<div class="row justify-content-center">
					<div class="col-lg-6 text-center">
						<div class="section-title">
							<h1>Best Sellers</h1>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
								dolore
								magna aliqua.</p>
						</div>
					</div>
				</div>
				<div class="row">
					{% for p in products_bestseller  %}

					<!-- single product -->
					<div class="col-lg-3 col-md-6">
						<div class="single-product">
							<a href="{% url 'product_management:singleproductview' p.id %}">
								<img class="img-fluid" src="{{p.images.url}}" alt="">
							</a>
							<div class="product-details">
								<h6>{{ p.product_name }}</h6>
								<div class="price">
									<h6>₹ {{ p.price }}</h6>
									<h6 class="l-through">₹ 2100.00</h6>
								</div>
		
								<div class="prd-bottom">
		
									<a href="#" class="social-info">
										<span class="ti-bag"></span>
										<p class="hover-text">add to cart</p>
									</a>
									<a href="{% url 'order_management:add_to_wishlist' p.id %}" class="social-info">
										<span class="lnr lnr-heart"></span>
										<p class="hover-text">Wishlist</p>
									</a>
									<a href=" {% url 'product_management:singleproductview' p.id %}" class="social-info">
										<span class="lnr lnr-move"></span>
										<p class="hover-text">view more</p>
									</a>
								</div>
							</div>
						</div>
					</div>
					{% endfor %}
	</section> 
	<!-- end product Area --> 

	

	{% include 'include/footer.html' %}
	<!-- End related-product Area -->
	<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
	<script src="{% static 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js' %}" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
	 crossorigin="anonymous"></script>
	<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
	<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
	<script src="{% static 'js/jquery.sticky.js' %}"></script>
	<script src="{% static 'js/nouislider.min.js' %}"></script>
	<script src="{% static 'js/countdown.js' %}"></script>
	<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<!--gmaps Js-->
	<script src="{% static 'https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE' %}"></script>
	<script src="{% static 'js/gmaps.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>

</body>

</html>

templates/reset_password_email.html
{% autoescape off %}  
Hi {{ user.first_name }},  
As requested ,please click below link to reset your password 
http:// {{ domain }}{% url 'resetpassword_validate' uidb64=uid token=token %}  
If you think it's not you ,please ignore this email
{% endautoescape %}

templates/userprofile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="main-body">
        <br>
        <h4 >My Profile</h4>

         <br>
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    {% if user.profile_pic %}
                    <img class="rounded-circle mt-5" width="150px" src="{{ request.user.profile_pic.url }}" alt="{{ request.user.username }} profile picture">
                {% else %}
                    <img class="rounded-circle mt-5" width="150px" src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="{{ user.username }} profile picture">
                {% endif %}

                    <div class="mt-3">
                      <h4>{{request.user.username}}</h4>
                      <p class="text-secondary mb-1">{{request.user.email}}</p>
                      <p class="text-muted font-size-sm"></p>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card mt-3">
                <ul class="list-group list-group-flush ">
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <div class="row">
                        <div class="col-sm-12 " >
                          <a   class=" text-warning " href="{% url 'further_management:myorders' %}" style="font-weight:bold;">My Orders</a>
                        </div>
                      </div>
    
                  </li>

                    <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                        <div class="row">
                            <div class="col-sm-12">
                              <a  class=" text-warning"  href="{% url 'changepassword' %}" style="font-weight:bold;">Change Password</a>
                            </div>
                          </div>
        
                      </li>
                      <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                        <div class="row">
                            <div class="col-sm-12">
                              <a  class=" text-warning"  href="{% url 'viewAddresses' %}" style="font-weight:bold;">View Addresses</a>
                            </div>
                          </div>
        
                      </li>

                </ul>
              </div>
            </div>
            

            <div class="col-md-8">
              {% include 'include/messagealert.html' %}

              <div class="d-flex justify-content-between align-items-center mb-3">


                <h4 class="text-right">Profile Details</h4>
    
            </div>

              <div class="card mb-3" >
                <div class="card-body">
                  <div class="row " style"color: black;">

                    <div class="col-md-6">
                      <label class="h6  ">First Name :</label>
                      {{request.user.first_name}}
                  </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-md-6">
                      <label class="h6">Last Name :</label>
                      {{request.user.last_name}}
                  </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-md-12">
                      <label class="h6">Mobile Number :</label>
                      {{request.user.phone}}
                  </div>
          
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-md-12">
                      <label class="h6">Address :</label>
                      {{request.user.address}}
                  </div>

                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-md-12">
                      <label class="h6">Post Code :</label>
                      {{request.user.pincode}}
                     </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-md-12">
                      <label class="h6">City :</label>
                      {{request.user.city}}
                  </div>

                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-md-12">
                      <label class="h6">State :</label>
                      {{request.user.state}}
                  </div>
                   </div>
                  <hr>


                  <div class="row" >
                    <div class="col-sm-12 form-group " >
                      <br>

                      <a class="btn btn-warning " style="background: linear-gradient(90deg, #ffba00 0%, #ff6c00 100%); color: #f2f2f2; margin-left: 339px; " href="{% url 'updateprofile' %}">Edit</a>

                    </div>

                  </div>
                </div>
              </div>
                <div class="col-sm-13 mb-5">
                  <div class="card h-100">
                  </div>
                </div>
              </div>



            </div>
          </div>

        </div>
    </div>

{% endblock %}

templates/viewaddresses.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container">
    <div class="main-body">

        <br>
        {% include 'include/messagealert.html' %}

        <h4 >My Addresses</h4>

         <br>
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    {% if user.profile_pic %}
                    <img class="rounded-circle mt-5" width="150px" src="{{ request.user.profile_pic.url }}" alt="{{ request.user.username }} profile picture">
                {% else %}
                    <img class="rounded-circle mt-5" width="150px" src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="{{ user.username }} profile picture">
                {% endif %}

                    <div class="mt-3">
                      <h4>{{request.user.username}}</h4>
                      <p class="text-secondary mb-1">{{request.user.email}}</p>
                      <p class="text-muted font-size-sm"></p>
                    </div>
                  </div>
                </div>
            </div>
            <div class="card mt-3">
                <ul class="list-group list-group-flush ">
                    <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                      <div class="row">
                        <div class="col-sm-12 " >
                          <a   class=" text-warning" href="{% url 'further_management:myorders' %}">My Orders</a>
                        </div>
                      </div>
    
                    </li>

                    <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                        <div class="row">
                            <div class="col-sm-12">
                              <a  class=" text-warning"  href="{% url 'changepassword' %}">Change Password</a>
                            </div>
                          </div>
        
                    </li>

                    <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                        <div class="row">
                            <div class="col-sm-12">
                              <a  class=" text-warning"  href="{% url 'viewAddresses' %}">View Addresses</a>
                            </div>
                          </div>
        
                    </li>
                </ul>
            </div>
        </div>   

        <section class="section-conten padding_top">

            <div class="container">
                <div class="row">
            
                    <main class="col-md-12">
            
                        <article class="card-md-12">
            
                            <header class="card-header ml-auto" style="background-color:#e8f0f2;">
                                <a href="{% url 'addNewAddress' 0 %}" class="btn btn-warning"  style="background: linear-gradient(90deg, #ffba00 0%, #ff6c00 100%); color: #f2f2f2;"role="button">+ Add New Address</a>
                            </header>
                         <div class="card-body">
                            <div class="row">
                                <div class="container">
                                    <h4 class="font-weight-bold mt-0 mb-4">Manage Addresses</h4>
                                    {% for address in AllAddress%}
                                    <div class="col-md-9 mt-4">
                                        <div class="row bg-white card addresses-item mb-4 border border-warning shadow">
                                            <div class="osahan-account-page-right shadow-sm bg-white p-4 h-100">
                                                <div class="tab-content" id="myTabContent">
                                                    <div class="tab-pane fade  active show" id="addresses" role="tabpanel" aria-labelledby="addresses-tab">
                                                        <h3 class="mb-1 text-secondary">{{address.first_name}} {{address.last_name}} {{address.str}}</h3>
                                                        <h5 class="mb-1 text-secondary">{{address.phone}}</h5>
                                                        <h5 class="mb-1 text-secondary">{{address.email}}</h5>
                                                        <p class="text-black">{{address.order_address}}<br/> {{address.city}}, {{address.state}}, {{address.country}}, <br/> Pin: {{address.zip_code}}</p>
                                                        <p class="mb-0 text-black font-weight-bold">
                                                            <a class="text-warning mr-3" href="{%url 'editAddress' address.id  %}">
                                                                EDIT
                                                            </a>
                                                          
                                                            <button type="button" data-toggle="modal" data-target="#a{{w.product.id}}" style="border:none; background-color:white; font-weight:bold; color:red;">DELETE</button>


                                                            <div class="modal fade" id="a{{w.product.id}}" tabindex="-1" role="dialog"aria-labelledby="exampleModal" aria-hidden="true">
                                                                <div class="modal-dialog" role="document">
                                                                    <div class="modal-content">
                                                                        <div class="modal-header">
                                                                            <h4 class="modal-title" id="exampleModal">Alert</h4>
                                                                            <button type="button" class="close" data-dismiss="modal"aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                                        </div>
                                                                        <div class="modal-body">
                                                                            <h5 class="modal-title" id="exampleModalLabel">You are Deleting {{address.first_name}} {{address.last_name}}'s address</h5>
                                                                        </div>
                                                                        <div class="modal-footer">
                                                                            <a href="{%url 'deleteAddress' address.id  %}" class="btn btn-danger btn-sm">Delete</a>
                                                                            <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
                                                                        </div>
                                                                    </div>
                                                                </div> 
                                                            </div>                           
                        
                                                        </p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    {% endfor%}
                                </div>
            
                            </div>
                          </div> 
                        </article>
            
                    </main>
                </div>
            </div>
        </section> 
    </div>
</div>
</div>
<br><br><br>
{% endblock %}