order_management/urls.py
from django.urls import path
from.import views
app_name = 'order_management'

urlpatterns=[
    path('wishlist/',views.wishlist,name='wishlist'),
    path('add_to_wishlist/<int:product_id>/',views.add_to_wishlist,name='add_to_wishlist'),
    path('remove_from_wishlist/<int:product_id>/',views.remove_from_wishlist,name='remove_from_wishlist'),
    path('cart',views.cart,name='cart'),
    path('add_to_cart/<int:product_id>/',views.add_to_cart,name='add_to_cart'),
    path('remove_from_cart/<int:product_id>/cart',views.remove_from_cart,name='remove_from_cart'),
    path('confirmation',views.confirmation,name='confirmation'),
    path('checkout',views.checkout,name='checkout'),
    path('remove_cart_quantity/<int:product_id>/',views.remove_cart_quantity,name='remove_cart_quantity'),
    path('add_cart_quantity/<int:product_id>/',views.add_cart_quantity,name='add_cart_quantity'),
    path('proceed_to_pay/',views.razorPayCheck,name="razorpaycheck"),
    path('place_order/', views.placeOrder, name='place_order'),
    path('order-complete/',views.orderComplete, name='order_complete'),
    path('cancel-order/<int:id>/',views.cancelOrder, name='cancel_order'),
]
        






    

product_management/urls.py
from django.urls import path
from.import views

app_name='product_management'
urlpatterns=[
    path('productlist/<int:pid>/',views.productlists,name='productlist'),
    path('singleproductview/<int:id>/',views.singleproductview,name='singleproductview'),
    path('search',views.search,name='search')

]

shoeplaza/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user_management.urls')),
    path('adminpanel/', include('admin_management.urls')),
    path('', include('product_management.urls')),
    path('', include('order_management.urls')),
    path('', include('further_management.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

templates/orders/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content  %}




    <!--================Cart Area =================-->
    <section class="cart_area">
        <div class="container">
            <div class="cart_inner">
                <div class="table-responsive">
                    <br>
                    {% include 'include/messagealert.html' %}
                    <br> 
                    <table class="table">

                        <thead>
                            <tr >
                                <th scope="col"><h5>Image</h5></th>
                                <th scope="col"><h5>Product_name</h5></th>
                                <th scope="col"><h5>Price</h5></th>
                                <th scope="col "><h5> Quantity</h5></th>
                                <th scope="col "><h5> Total</h5></th>
                                <th scope="col"><h5>Remove</h5></th>

                            </tr>
                        </thead>

                        <tbody>
                            {% if cart_items %} 
                            {% for c in cart_items %}
    
                            <tr >
                                <td>
                                        <div class="d-flex" >
                                            <img style="width: 80px;" src="{{c.product.images.url}}" alt="">
                                        </div>
                                </td>
                                <td>
                                    <h5><p>{{c.product.product_name}}</p></h5>
                                </td>
                                <td>
                                    <h5>₹{{c.product.price}}</h5>
                                </td>
                                
                                <td>
                                    <div class="product_count">

                                        <a href="{% url 'order_management:remove_cart_quantity' c.product.id %}" > <i class="fa fa-minus text-warning"></i></a>
                                        <input class="form-contrl col-md input-number" name="quantity" type="text" value="{{c.quantity}}" min="0" max="100">
                                        <a href="{% url 'order_management:add_cart_quantity' c.product.id %}" > <i class="fa fa-plus text-warning"></i></a>
                                      </div>
                                                      </td>
                                <td> <h5>₹ {% widthratio c.product.price 1 c.quantity%}</h5></td>

                                <td>                               
                                    <button type="button" class="btn btn-link text-danger" data-toggle="modal"data-target="#c{{w.product.id}}"><i class="bi bi-trash" style="font-size: 24px;"></i></button>


                                    <div class="modal fade" id="c{{w.product.id}}" tabindex="-1" role="dialog"aria-labelledby="exampleModal" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h4 class="modal-title" id="exampleModal">Alert</h4>
                                                    <button type="button" class="close" data-dismiss="modal"aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                                </div>
                                                <div class="modal-body">
                                                    <h5 class="modal-title" id="exampleModalLabel">You are Deleting {{c.product.product_name}}</h5>
                                                </div>
                                                <div class="modal-footer">
                                                    <a href="{% url 'order_management:remove_from_cart' c.product.id %}" class="btn btn-danger btn-sm">Delete</a>
                                                    <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
                                                </div>
                                            </div>
                                        </div> 
                                    </div>                           
        
                                </td>

                            </tr>
                            {% endfor %}

                        


                            <tr>
                                <td></td><td></td><td></td><td>
                                    <h5>Subtotal</h5>
                                </td>
                                <td>
                                    <h5>₹ {{total}}</h5>
                                </td><td></td>
                            </tr>
                            <tr class="out_button_area">
                                <td></td><td></td><td></td><td></td><td></td>
                                <td>
                                    <div class="checkout_btn_inner d-flex align-items-space-between">
                                        
                                        <a class="gray_btn" href="{% url 'product_management:productlist' 0 %}">Continue Shopping</a>
                                        
                                        <a class="primary-btn" href="{% url 'order_management:checkout' %}">Proceed to checkout</a>
                                    </div>
                                </td>
                            </tr> 

                        </tbody>
                        {% else %}

                        <tr>
                            <hr>
                            <div style="text-align: center; ">
                                <h4 class=" text-danger">Cart is Empty</h4>
                              </div>
                             {% endif %}
                        </tr>
    
                    </table>
                </div>
            </div>
        </div>
    </section>
    <!--================End Cart Area =================-->






{% endblock  %}

templates/orders/checkout.html
{% extends 'base.html' %}
{% block content  %}
{% load static %}

<section class="checkout_area section_gap">
    <div class="container">
   
             {% include 'include/messagealert.html' %}
      <div class="card " style="background-color: #e8f0f5; width:50vw;">
        <div class="card-body">
            <form action="{% url 'order_management:checkout' %}" id="coupon-form" method="POST" required>
              {%csrf_token%}
                <div class="form-group"> <label>Have coupon?</label>
                    <div class="input-group">
                      <input type="hidden" class="form-control"value="{{grand_total}}" name="grand_total" required/>
                      <input type="hidden" class="form-control" value="{{addressSelected.id}}" name="addressSelected" required />
                      <input type="text" class="form-control coupon" name="couponCode" placeholder="Coupon code">
                      <span class="input-group-append">
                        <button class="btn btn-warning btn-apply coupon" style="background: linear-gradient(90deg, #ffba00 0%, #ff6c00 100%); color: #f2f2f2;"  {% if discount %}disabled{% endif %} >Apply</button>
                      </span>
                    </div>
                </div>
            </form>
        </div>
      </div>
    
      <br><br>
        <div class="billing_details">
            <div class="row">
                <div class="col-lg-8">
                    <section class="cart_area padding_top">
                      <form class="row contact_form" action="{% url 'order_management:confirmation' %}" method="POST">
                        {% csrf_token %}
                        <div class="container">
                          <div class="cart_inner">
                       <h4 class="font-weight-bold mt-0 mb-4">Select your Delivery Address</h4>

                 <!-- Default unchecked -->
                
                <header class="card-header mr-auto" style="background-color:#e8f0f2;">
                
                  <a class="tp_btn" style="background: linear-gradient(90deg, #ffba00 0%, #ff6c00 100%);  color: #f2f2f2;" href="{% url 'addNewAddress' 1 %}">Add new address</a>
                </header>
                
                    {% for address in addresses%}
                    <div class="custom-control custom-checkbox" >
                      <input type="radio" class="custom-control-input " id="{{address}}" name="addressSelected" value="{{address.id}}" checked>

                        <label class="custom-control-label" for="{{address}}" style="width: 100%;">
                          <div class="col-md-9">
                            <div class="row bg-white card addresses-item mb-2 mt-3 border border-warning shadow">
                              <div class="osahan-account-page-right shadow-sm bg-white p-4 h-100" >
                                <div class="tab-content" id="myTabContent">
                                  <div class="tab-pane fade  active show" id="addresses" role="tabpanel" aria-labelledby="addresses-tab">
                                    <h3 class="mb-1 text-secondary"> {{address.first_name}}</h3>
                                    <h5 class="mb-1 text-secondary">{{address.phone}}</h5>
                                    <h5 class="mb-1 text-secondary">{{address.email}}</h5>
                                    <p class="text-black">{{address.full_address}}</p>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </label>
                      </div>
                    {% endfor%}
                    
                      </div>
                    </div>

                </section>
                
                 <!-- Coupon Related Fields -->

                </div>
                <div class="col-lg-4">
                    <div class="order_box">
                        <h2>Your Order</h2>
                        <ul class="list">
                            <li><a href="#">Product <span>Total</span></a></li>
                            {% for cart_item in cart_items%}
                            <li>
                                
                                <a href="#">
                                  {{cart_item.product.product_name}}
                                  <span class="price">₹ {{cart_item.product.price}}</span>
                                </a>
                                </li>
                            </li>
                                                            
                            {%endfor%}
                        </ul>
                        <ul class="list list_2">
                            <li><a href="#">Subtotal<span>₹ {{total}}</span></a></li>
                            <li><a href="#">Tax <span>₹ {{tax}}</span></a></li>
                            <li><a href="#">Grand Total <span>₹ {{grand_total}}</span></a></li>
                            {% if discount %}
                            <li><span>Coupon Applied.</span></li>
                            <li><a href="#">Coupon Code : {{coupon.code}}</a></li>
                            <li><a href="#">Coupon Discount({{coupon.discount}}%)<span>₹ {{coupon_discount}}</span></a></li>
                            <li><a href="#">Payable Amount<span>₹ {{amountToBePaid}}</span></a></li>
                            {%endif%}
                            
                        </ul>
                        <input type="hidden" class="form-control" value="{{total}}" name="total" required/>
                        <input type="hidden" class="form-control" value="{{grand_total}}" name="grand_total" required/>
                        <input type="hidden" class="form-control" value="{{amountToBePaid}}" name="amountToBePaid" required/>
                        <input type="hidden" class="form-control" value="{{coupon_discount}}" name="coupon_discount" required/>
                        <input type="hidden" class="form-control" value="{{tax}}" name="tax" required/>
                        <input type="hidden" class="form-control" id="couponCode" value="{{coupon.code}}" name="couponCode" required/>
 
                        <br><br>
                        <div class="d-flex justify-content-center align-items-center">
                          <button type="submit" value="submit" class="primary-btn border-0 w-100">Place Order</button>
                        </div>
                                                
                      </div>
                </div>
            </div>
        </div>
    </div>
  </form>
</section>

{% endblock  %}

templates/orders/confirmation.html
{% extends 'base.html' %}
{% block content %}
{% load static %}



	<!--================Order Details Area =================-->
	<section class="order_details section_gap">
		<div class="container">
			<h3 class="title_confirmation">Confirmation Of Your Purchase.</h3>
			{% include 'include/messagealert.html' %}
			<form  action=" {% url 'order_management:place_order' %}" method="POST">
			{% csrf_token %}
            <div class="order_details_table">
				<h4>Shipping Address</h4>
				<hr>

				<div class="table-responsive">
					<ul class="list">
						<h5>  <li> <span>Name</span> : {{addressSelected.first_name}} {{addressSelected.last_name}}</li></h5>
						<h5><li><span>Address</span> : {{addressSelected.order_address}} ,{{addressSelected.city}} , {{addressSelected.state}}</li></h5>
						<h5><li><span>Country </span> : {{addressSelected.country}}</li></h5>
						<h5><li><span>Pin Code </span> : {{addressSelected.zip_code}}</li></h5>
						<h5><li><span>Phone</span> :{{addressSelected.phone}} </li></h5>
						<h5><li><span>Email </span> : {{addressSelected.email}}</li></h5>	
					</ul>
				</div>
			</div>

			<!-- Address Related Fields -->
			 <input type="hidden" class="form-control"  value="{{addressSelected.id}}" name="addressSelected" placeholder="First Name"required />
			 <input type="hidden" class="form-control" value="{{addressSelected.first_name}}" name="first_name"placeholder="First Name"required />
			 <input type="hidden" class="form-control" id="last"value="{{addressSelected.last_name}}" name="last_name"placeholder="Last Name" required/>
			 <input type="hidden" class="form-control" id="phone"value="{{addressSelected.phone}}" name="phone"placeholder="Phone Number"required/>
			 <input type="hidden" class="form-control" id="email"value="{{addressSelected.email}}" name="email"placeholder="Email" required/>
			 <input type="hidden" class="form-control" id="add1" value="{{addressSelected.order_address}}" name="address_line_1" placeholder="Address 1"required/>
			 <input type="hidden" class="form-control" id="city" value="{{addressSelected.city}}" name="city"placeholder="City" required/>
			 <input type="hidden" class="form-control" id="state" value="{{addressSelected.state}}" name="state"placeholder="State" required/>
			 <input type="hidden" class="form-control" id="country" value="{{addressSelected.country}}" name="country"placeholder="Country" required/>
			 <input type="hidden" class="form-control" id="zip_code" name="zip_code"value="{{addressSelected.zip_code}}" placeholder="Postcode/ZIP" required/>
			 <!-- Coupon Related Fields -->
			 <input type="hidden" class="form-control" value="{{total}}" name="total" required/>
			 <input type="hidden" class="form-control" value="{{grand_total}}" name="grand_total" required/>
			 <input type="hidden" class="form-control" value="{{amountToBePaid}}" name="amountToBePaid" required/>
			 <input type="hidden" class="form-control" id="couponCode" value="{{couponCode}}" name="couponCode" required/>
			 <input type="hidden" class="form-control" value="{{coupon_discount}}" name="coupon_discount" required/>
			<!-- Cod Related Fields -->
			 <input type="hidden" value="COD"name="payment_method">
 
            <br>
			<div class="order_box">
				<h2>Your Order Summary</h2>
				<ul class="list">
					<li><a href="#">Product <span>Total</span></a></li>
					{% for cart_item in cart_items%}
					<li><a href="#">{{cart_item.product.product_name}}<span class="price">₹ {{cart_item.product.price}}</span></a></li>								
					{%endfor%}
				</ul>
				<ul class="list list_2">
					<li><a href="#">Subtotal<span>₹ {{total}}</span></a></li>
					<li><a href="#">Tax <span>₹ {{tax}}</span></a></li>
					<li><a href="#">Grand Total <span>₹ {{grand_total}}</span></a></li>
					<li><a href="#">Coupon Discount<span>₹ {{coupon_discount}}</span></a></li>
					<li><a href="#">Payable Amount<span>₹ {{amountToBePaid}}</span></a></li>
				</ul>
				<br><br>
				<div class="d-flex justify-content-center align-items-center">
				  <button type="submit" value="submit" class="primary-btn border-0 w-25">Cash on delivery</button>&nbsp&nbsp&nbsp
		</form>
		<button type="button" id="payWithRazorpay"  class="primary-btn border-0 w-25">Pay with Razorpay</button>				</div>
        </div>
	</div>

</section>
<script src="https://code.jquery.com/jquery-3.6.4.min.js" integrity="sha256-oP6HI9z1XaZNBrJURtCoUT5SUnxFr8s3BzRl+cbzUq8=" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<script src="{% static 'js/checkout.js' %}"></script>



{% if msg %}
<script>
  console.log("here");
  swal("Error!", "{{msg}}", "info");

</script>
{% endif %}
{% endblock  %}
<!--================End Order Details Area =================-->

templates/orders/order_completed.html
{% extends 'base.html' %}
{% load static %}

{% block  content %}	
<br><br><br><br><br><br><br><br>

{% include 'include/messagealert.html' %}

<div class="card">
<div class="card-body">
<div class="container mb-5 mt-3">
  <div class="row d-flex align-items-baseline">
    <div class="col-xl-9">
      <p style="color: #7e8d9f;font-size: 20px;">Invoice >> <strong>Order ID: {{order.order_number}}</strong></p>
     
    </div>
    <hr>
    <div>
      <button class="btn btn-warning ml-left" id="printInvoice">Print</button>
    </div>
  </div>
  <br><br>

  <div class="container">
    <div class="col-md-12">
      <div class="text-center">
        <i class="fab fa-mdb fa-4x ms-0" style="color:#5d9fc5 ;"></i>
        <p class="pt-0"><h3> Shoeplaza India Pvt Ltd</h3></p>
      </div>

    </div>


    <div class="row">
      <div class="col-xl-8 ">
        <ul class="list-unstyled">
          <li class="text-muted"><h4>To:</h4> <span style="color:#5d9fc5 ;"><h5>{{order.address.full_name}}</h5></span></li>
          <li class="text-muted"><h5>{{order.address.order_address}}, {{order.address.city}}</h5></li>
          <li class="text-muted"><h5>{{order.address.state}}, {{order.address.country}}</h5></li>
          <li class="text-muted"><h5><i class="fa fa-phone"></i> {{order.address.phone}}</h5></li>
          {% comment %} <li class="text-muted"><h5><i class="fa fa-phone"></i> {{order.address.email}}</h5></li> {% endcomment %}

        </ul>
      </div>
      <div class="col-xl-4">
        <p class="text-muted"><h4>Invoice</p></h4>
        <ul class="list-unstyled">
          <li class="text-muted"><i class="fa fa-circle" style="color:#40464c ;"></i> <span
            class="fw-bold">Payment Method: </span>{{ order.payment.payment_method }}</li>
          <li class="text-muted"><i class="fa fa-circle" style="color:#40464c  ;"></i> <span
              class="fw-bold">Payment ID: </span>{{ order.payment.payment_id }}</li>
          <li class="text-muted"><i class="fa fa-circle" style="color:#40464c  ;"></i> <span
              class="fw-bold">Creation Date: </span>{{order.created_at}}</li>
          <li class="text-muted"><i class="fa fa-circle" style="color:#40464c  ;"></i> <span
              class="me-1 fw-bold">Ordered From: </span>{{order.user.email}}</li>
        </ul>
      </div>
    </div>
    <div class="row my-2 mx-1 justify-content-center">
      <table class="table table-striped table-borderless">
        <thead style="background-color: #828bb3;" class="text-white">
          <tr>
            <th scope="col">Product</th>
            <th scope="col">Unit Price</th>
            <th scope="col">Quantity</th>
            <th scope="col">Amount</th>
          </tr>
        </thead>
        <tbody>
            {% for item in orderitems %}
          <tr>
            <td>{{item.product.product_name}}</td>
            <td>₹ {{ item.product.price}}</td>
            <td>{{ item.quantity}}</td>
            <td>₹ {{ item.sub_total}}</td>
          </tr>
          {% endfor %}
        </tbody>

      </table>
    </div>
    <div class="row">

      <div class="col-xl-3 ml-4">
        <h4><ul class="list-unstyled ">
          <li class="text-muted ms-3"><span class="text-black me-4">SubTotal: </span>{{total}}</li>
          <li class="text-muted ms-3 mt-2"><span class="text-black me-4">Tax(5%): </span>{{order.tax}}</li>
          <li class="text-muted ms-3"><span class="text-black me-4"> Sum Total: </span><span>{{order.order_total}}</span></li>
            <li class="text-muted ms-3"><span class="text-black me-4"> Discount: </span><span>{{order.order_discount}}</span></li>
            <li class="text-muted ms-3"><span class="text-black me-4"> Grand Total: </span><span>{{order.paid_amount}}</span></li>
          </ul></h4>

      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-xl-10">
        <p>Thank you for purchasing from us.</p>
      </div>

    </div>

  </div>
</div>
</div>
</div>

<script src="{% static  'js/jquery-3.6.0.min.js'%}"></script>
<script>
  document.getElementById("printInvoice").addEventListener("click", function() {
      window.print();
  });

</script>


<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
<script src="{% static 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js' %}" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4"
 crossorigin="anonymous"></script>
<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/jquery.sticky.js' %}"></script>
<script src="{% static 'js/nouislider.min.js' %}"></script>
<script src="{% static 'js/countdown.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<!--gmaps Js-->
<script src="{% static 'https://maps.googleapis.com/maps/api/js?key=AIzaSyCjCGmQ0Uq4exrzdcL6rvxywDDOvfAu6eE' %}"></script>
<script src="{% static 'js/gmaps.min.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
<br><br><br><br><br><br><br><br>

{% endblock  %}

templates/orders/wishlist.html
{% extends 'base.html' %}
{% block content %}
{% load static %}


<body>
    <!--================Cart Area =================-->
    <section class="cart_area">
        <div class="container">
            <div class="cart_inner">
                <div class="table-responsive">
                    <br>
                    {% include 'include/messagealert.html' %}
                       <br> 
                    <table class="table">        
                        <thead>
                            <tr >
                                <th scope="col"><h5>Image</h5></th>
                                <th scope="col"><h5>Product_name</h5></th>
                                <th scope="col"><h5>Price</h5></th>
                                <th scope="col "><h5> Add To Cart</h5></th>
                                <th scope="col"><h5>Remove</h5></th>

                            </tr>
                        </thead>
                        {% if wishlist_items %}
                        {% for w in wishlist_items %}

                        <tbody>
                            <tr >
                                <td>
                                        <div class="d-flex">
                                            <img src="{{w.product.images.url}}" alt="" style="width:100px;">
                                        </div>
                                </td>
                                <td>
                                    <h5>                                       
                                        <p>{{w.product.product_name}}</p>
                                    </h5>
                                </td>
                            <td>
                                    <h5>₹{{w.product.price}}</h5>
                                </td>
                                <td>
                                    <div class="details-action-col col-7"> 
                                        {% if w.product.stock > 0 %} 
                                        
                                            
                                            <div class="product-details-quantity-container">
                                                {% comment %} <input type="hidden"  name="quantity" value="1" min="1" max="10" step="1"> {% endcomment %}
                                                
                                                <a href="{% url 'order_management:add_to_cart' w.product.id %}" style="border:none; background-color:white; font-weight:bold; color:orange;"><i class="bi bi-cart-plus" style="font-size: 24px;"></i> Add to Cart</a>
                                    
                                            </div>
                                        </form>
                                        {% else %}
                                        <a href="" class="btn btn-block btn-outline-primary-2 disabled">Out of Stock</a>
                                        {%endif%}    
                                    </div>                      
                                 </td>
                                <td>                                   
                                    <button type="button" class="btn btn-link text-danger" data-toggle="modal"data-target="#w{{w.product.id}}"><i class="bi bi-trash" style="font-size: 24px;"></i></button>
                                 

                                </div>
                            </td>
                            <div class="modal fade" id="w{{w.product.id}}" tabindex="-1" role="dialog"aria-labelledby="exampleModal" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h4 class="modal-title" id="exampleModal">Alert</h4>
                                            <button type="button" class="close" data-dismiss="modal"aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        </div>
                                        <div class="modal-body">
                                            <h5 class="modal-title" id="exampleModalLabel">You are Deleting {{w.product.product_name}}</h5>
                                        </div>
                                        <div class="modal-footer">
                                            <a href="{% url 'order_management:remove_from_wishlist' w.product.id %}" class="btn btn-danger btn-sm">Delete</a>
                                            <button type="button" class="btn btn-secondary btn-sm" data-dismiss="modal">Close</button>
                                        </div>
                                    </div>
                                </div> 
                            </div>                           

                            </tr>
                            {% endfor %}
                            
                        </tbody>
                        {% else %}
                        <tr>
                            <hr>
                            <div style="text-align: center; ">
                                <h4 class=" text-danger">Wishlist is Empty</h4>
                              </div>
                             {% endif %}
                        </tr>


                    </table>
                </div>
            </div>
        </div>
    </section>
    <!--================End Cart Area =================-->
{% endblock  %}